# Created at 2023-02-22T15:10:40.523
TestSet has not finished before stream error has appeared >> initializing exit by non-null configuration: null
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:398)
	at org.apache.maven.surefire.booter.MasterProcessCommand.decode(MasterProcessCommand.java:115)
	at org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:391)
	at java.base/java.lang.Thread.run(Thread.java:833)


# Created at 2023-02-22T15:10:41.924
Unexpected IOException with stream: 2023-02-22 15:10:41.921  INFO 8108 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...


# Created at 2023-02-22T15:10:42.308
Unexpected IOException with stream: 2023-02-22 15:10:42.307  INFO 8108 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.


# Created at 2023-02-22T15:10:42.404
Unexpected IOException with stream: 2023-02-22 15:10:42.404  INFO 8108 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]


# Created at 2023-02-22T15:10:42.531
Unexpected IOException with stream: 2023-02-22 15:10:42.530  INFO 8108 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.4.Final


# Created at 2023-02-22T15:10:42.926
Unexpected IOException with stream: 2023-02-22 15:10:42.925  INFO 8108 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}


# Created at 2023-02-22T15:10:43.260
Unexpected IOException with stream: 2023-02-22 15:10:43.259  INFO 8108 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect


# Created at 2023-02-22T15:10:44.360
Unexpected IOException with stream: 2023-02-22 15:10:44.359  INFO 8108 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]


# Created at 2023-02-22T15:10:44.533
Unexpected IOException with stream: 2023-02-22 15:10:44.533  INFO 8108 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'


# Created at 2023-02-22T15:10:45.315
Unexpected IOException with stream: 2023-02-22 15:10:45.312  WARN 8108 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appController': Unsatisfied dependency expressed through field 'personRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'personRepository' defined in com.kth.iv1201.recruitmentApp.repository.PersonRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract com.kth.iv1201.recruitmentApp.domain.Person com.kth.iv1201.recruitmentApp.repository.PersonRepository.findByUsername(java.lang.String)! Reason: Validation failed for query for method public abstract com.kth.iv1201.recruitmentApp.domain.Person com.kth.iv1201.recruitmentApp.repository.PersonRepository.findByUsername(java.lang.String)!; nested exception is java.lang.IllegalArgumentException: Validation failed for query for method public abstract com.kth.iv1201.recruitmentApp.domain.Person com.kth.iv1201.recruitmentApp.repository.PersonRepository.findByUsername(java.lang.String)!


# Created at 2023-02-22T15:10:45.318
Unexpected IOException with stream: 2023-02-22 15:10:45.316  INFO 8108 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'


# Created at 2023-02-22T15:10:45.320
Unexpected IOException with stream: 2023-02-22 15:10:45.320  INFO 8108 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...


# Created at 2023-02-22T15:10:45.342
Unexpected IOException with stream: 2023-02-22 15:10:45.342  INFO 8108 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.


